# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c68bb380c3478e4a67b1c585bda2b1f4edb766a125cbfbe3766ae65f0309257ecd06742c7c21e85ca208d2eb5a874d3d4fb35563178f02fe97d334465873bc79

test:
  secret_key_base: e356edf6403e9d262adc28f8639eb9fff5b98b2d5131e8bc1aaead35fff95a6ce60fbfac2d9cb7d061f4f5eb50ff7e99c6a8bc754707e77fff3c77b59bab6343

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
